In [2]:
import numpy as np
print(np.__version__)


2.5.2


In [3]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [5]:
np.random.randint(low=4,high=16,size=5)


array([ 8, 15, 12,  4,  8], dtype=int32)

In [7]:
numbers = np.arange(-10,11,2)
numbers

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [14]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])